name: Build Flutter App for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Flutter doctor
      run: flutter doctor

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Flutter app for Windows
      run: flutter build windows

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/windows/runner/Release
